/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ibtrader.data.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the IBOrder service. Represents a row in the &quot;ibtrader_IBOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ibtrader.data.model.impl.IBOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ibtrader.data.model.impl.IBOrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IBOrder
 * @see com.ibtrader.data.model.impl.IBOrderImpl
 * @see com.ibtrader.data.model.impl.IBOrderModelImpl
 * @generated
 */
@ProviderType
public interface IBOrderModel extends BaseModel<IBOrder>, ShardedModel,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a i b order model instance should use the {@link IBOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this i b order.
	 *
	 * @return the primary key of this i b order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this i b order.
	 *
	 * @param primaryKey the primary key of this i b order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this i b order.
	 *
	 * @return the uuid of this i b order
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this i b order.
	 *
	 * @param uuid the uuid of this i b order
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the order ID pk of this i b order.
	 *
	 * @return the order ID pk of this i b order
	 */
	public long getOrderIdPk();

	/**
	 * Sets the order ID pk of this i b order.
	 *
	 * @param orderIdPk the order ID pk of this i b order
	 */
	public void setOrderIdPk(long orderIdPk);

	/**
	 * Returns the orders ID of this i b order.
	 *
	 * @return the orders ID of this i b order
	 */
	public long getOrdersId();

	/**
	 * Sets the orders ID of this i b order.
	 *
	 * @param ordersId the orders ID of this i b order
	 */
	public void setOrdersId(long ordersId);

	/**
	 * Returns the group ID of this i b order.
	 *
	 * @return the group ID of this i b order
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this i b order.
	 *
	 * @param groupId the group ID of this i b order
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this i b order.
	 *
	 * @return the company ID of this i b order
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this i b order.
	 *
	 * @param companyId the company ID of this i b order
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the share i d of this i b order.
	 *
	 * @return the share i d of this i b order
	 */
	public long getShareID();

	/**
	 * Sets the share i d of this i b order.
	 *
	 * @param shareID the share i d of this i b order
	 */
	public void setShareID(long shareID);

	/**
	 * Returns the checked of this i b order.
	 *
	 * @return the checked of this i b order
	 */
	public boolean getChecked();

	/**
	 * Returns <code>true</code> if this i b order is checked.
	 *
	 * @return <code>true</code> if this i b order is checked; <code>false</code> otherwise
	 */
	public boolean isChecked();

	/**
	 * Sets whether this i b order is checked.
	 *
	 * @param checked the checked of this i b order
	 */
	public void setChecked(boolean checked);

	/**
	 * Returns the create date of this i b order.
	 *
	 * @return the create date of this i b order
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this i b order.
	 *
	 * @param createDate the create date of this i b order
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this i b order.
	 *
	 * @return the modified date of this i b order
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this i b order.
	 *
	 * @param modifiedDate the modified date of this i b order
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ibclient ID of this i b order.
	 *
	 * @return the ibclient ID of this i b order
	 */
	public long getIbclientId();

	/**
	 * Sets the ibclient ID of this i b order.
	 *
	 * @param ibclientId the ibclient ID of this i b order
	 */
	public void setIbclientId(long ibclientId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(IBOrder ibOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<IBOrder> toCacheModel();

	@Override
	public IBOrder toEscapedModel();

	@Override
	public IBOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}