/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ibtrader.data.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Order service. Represents a row in the &quot;ibtrader_Order&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ibtrader.data.model.impl.OrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ibtrader.data.model.impl.OrderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Order
 * @see com.ibtrader.data.model.impl.OrderImpl
 * @see com.ibtrader.data.model.impl.OrderModelImpl
 * @generated
 */
@ProviderType
public interface OrderModel extends BaseModel<Order>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order model instance should use the {@link Order} interface instead.
	 */

	/**
	 * Returns the primary key of this order.
	 *
	 * @return the primary key of this order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order.
	 *
	 * @param primaryKey the primary key of this order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this order.
	 *
	 * @return the uuid of this order
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this order.
	 *
	 * @param uuid the uuid of this order
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the orders ID of this order.
	 *
	 * @return the orders ID of this order
	 */
	public long getOrdersId();

	/**
	 * Sets the orders ID of this order.
	 *
	 * @param ordersId the orders ID of this order
	 */
	public void setOrdersId(long ordersId);

	/**
	 * Returns the group ID of this order.
	 *
	 * @return the group ID of this order
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this order.
	 *
	 * @param groupId the group ID of this order
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this order.
	 *
	 * @return the company ID of this order
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this order.
	 *
	 * @param companyId the company ID of this order
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the order i d of this order.
	 *
	 * @return the order i d of this order
	 */
	public long getOrderID();

	/**
	 * Sets the order i d of this order.
	 *
	 * @param orderID the order i d of this order
	 */
	public void setOrderID(long orderID);

	/**
	 * Returns the share i d of this order.
	 *
	 * @return the share i d of this order
	 */
	public long getShareID();

	/**
	 * Sets the share i d of this order.
	 *
	 * @param shareID the share i d of this order
	 */
	public void setShareID(long shareID);

	/**
	 * Returns the checked of this order.
	 *
	 * @return the checked of this order
	 */
	public boolean getChecked();

	/**
	 * Returns <code>true</code> if this order is checked.
	 *
	 * @return <code>true</code> if this order is checked; <code>false</code> otherwise
	 */
	public boolean isChecked();

	/**
	 * Sets whether this order is checked.
	 *
	 * @param checked the checked of this order
	 */
	public void setChecked(boolean checked);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Order order);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Order> toCacheModel();

	@Override
	public Order toEscapedModel();

	@Override
	public Order toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}