/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ibtrader.data.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.ibtrader.data.model.MarkeShare;
import com.ibtrader.data.model.MarkeShareModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MarkeShare service. Represents a row in the &quot;ibtrader_MarkeShare&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MarkeShareModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarkeShareImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarkeShareImpl
 * @see MarkeShare
 * @see MarkeShareModel
 * @generated
 */
@ProviderType
public class MarkeShareModelImpl extends BaseModelImpl<MarkeShare>
	implements MarkeShareModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a marke share model instance should use the {@link MarkeShare} interface instead.
	 */
	public static final String TABLE_NAME = "ibtrader_MarkeShare";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "marketshareId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "shareId", Types.BIGINT },
			{ "marketId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("marketshareId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("shareId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("marketId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table ibtrader_MarkeShare (uuid_ VARCHAR(75) null,marketshareId LONG not null primary key,groupId LONG,companyId LONG,shareId LONG,marketId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ibtrader_MarkeShare";
	public static final String ORDER_BY_JPQL = " ORDER BY markeShare.marketshareId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ibtrader_MarkeShare.marketshareId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.ibtrader.data.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ibtrader.data.model.MarkeShare"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.ibtrader.data.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ibtrader.data.model.MarkeShare"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.ibtrader.data.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ibtrader.data.model.MarkeShare"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long MARKETSHAREID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.ibtrader.data.service.util.ServiceProps.get(
				"lock.expiration.time.com.ibtrader.data.model.MarkeShare"));

	public MarkeShareModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _marketshareId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMarketshareId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _marketshareId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MarkeShare.class;
	}

	@Override
	public String getModelClassName() {
		return MarkeShare.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("marketshareId", getMarketshareId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("shareId", getShareId());
		attributes.put("marketId", getMarketId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long marketshareId = (Long)attributes.get("marketshareId");

		if (marketshareId != null) {
			setMarketshareId(marketshareId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long shareId = (Long)attributes.get("shareId");

		if (shareId != null) {
			setShareId(shareId);
		}

		Long marketId = (Long)attributes.get("marketId");

		if (marketId != null) {
			setMarketId(marketId);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getMarketshareId() {
		return _marketshareId;
	}

	@Override
	public void setMarketshareId(long marketshareId) {
		_marketshareId = marketshareId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getShareId() {
		return _shareId;
	}

	@Override
	public void setShareId(long shareId) {
		_shareId = shareId;
	}

	@Override
	public long getMarketId() {
		return _marketId;
	}

	@Override
	public void setMarketId(long marketId) {
		_marketId = marketId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MarkeShare.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MarkeShare toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MarkeShare)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MarkeShareImpl markeShareImpl = new MarkeShareImpl();

		markeShareImpl.setUuid(getUuid());
		markeShareImpl.setMarketshareId(getMarketshareId());
		markeShareImpl.setGroupId(getGroupId());
		markeShareImpl.setCompanyId(getCompanyId());
		markeShareImpl.setShareId(getShareId());
		markeShareImpl.setMarketId(getMarketId());

		markeShareImpl.resetOriginalValues();

		return markeShareImpl;
	}

	@Override
	public int compareTo(MarkeShare markeShare) {
		long primaryKey = markeShare.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MarkeShare)) {
			return false;
		}

		MarkeShare markeShare = (MarkeShare)obj;

		long primaryKey = markeShare.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MarkeShareModelImpl markeShareModelImpl = this;

		markeShareModelImpl._originalUuid = markeShareModelImpl._uuid;

		markeShareModelImpl._originalGroupId = markeShareModelImpl._groupId;

		markeShareModelImpl._setOriginalGroupId = false;

		markeShareModelImpl._originalCompanyId = markeShareModelImpl._companyId;

		markeShareModelImpl._setOriginalCompanyId = false;

		markeShareModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MarkeShare> toCacheModel() {
		MarkeShareCacheModel markeShareCacheModel = new MarkeShareCacheModel();

		markeShareCacheModel.uuid = getUuid();

		String uuid = markeShareCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			markeShareCacheModel.uuid = null;
		}

		markeShareCacheModel.marketshareId = getMarketshareId();

		markeShareCacheModel.groupId = getGroupId();

		markeShareCacheModel.companyId = getCompanyId();

		markeShareCacheModel.shareId = getShareId();

		markeShareCacheModel.marketId = getMarketId();

		return markeShareCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", marketshareId=");
		sb.append(getMarketshareId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", shareId=");
		sb.append(getShareId());
		sb.append(", marketId=");
		sb.append(getMarketId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.ibtrader.data.model.MarkeShare");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marketshareId</column-name><column-value><![CDATA[");
		sb.append(getMarketshareId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shareId</column-name><column-value><![CDATA[");
		sb.append(getShareId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marketId</column-name><column-value><![CDATA[");
		sb.append(getMarketId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MarkeShare.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MarkeShare.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _marketshareId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _shareId;
	private long _marketId;
	private long _columnBitmask;
	private MarkeShare _escapedModel;
}